name: hackathon_env
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - scikit-learn>=1.2
  - pandas>=2.0
  - numpy>=1.24
  - matplotlib>=3.7
  - pip:
      - transformers>=4.40,<5
      - datasets>=2.18
      - accelerate>=0.30
      - evaluate>=0.4
      - xgboost>=1.7
      - joblib>=1.3
